var data = {
  aqi: 28,
  astronomical: {
    astronomical_twilight_begin: "04:51",
    astronomical_twilight_end: "21:32",
    civil_twilight_begin: "06:09",
    civil_twilight_end: "20:14",
    day_length: "06:02",
    moon: { age: "", moonrise: "", moonset: "", phase: "" },
    nautical_twilight_begin: "05:31",
    nautical_twilight_end: "20:52",
    solar_noon: "13:12",
    sunrise: "06:40",
    sunset: "19:43",
  },
  bestDayToGetOutside: "",
  chancePrecipitation: 10,
  chanceThunder: 0,
  currentConditions: "Chance Rain Showers",
  currentTemp: 46,
  dayLength: "",
  detailedForecast:
    "A chance of rain showers. Mostly cloudy, with a high near 46. West northwest wind 10 to 15 mph, with gusts as high as 21 mph. Chance of precipitation is 50%. New rainfall amounts less than a tenth of an inch possible.",
  humitidy: 66,
  isDaytime: true,
  pressure: 30.09,
  pressureDirection: "falling",
  shortForecast: "Chance Rain Showers",
  snow: { chanceSnow: 0, snowAccumInchesMax: 0, snowAccumInchesMin: 0 },
  todayHigh: 46,
  todayLow: 36,
  tomorrowHigh: 48,
  tomorrowLow: 38,
  uvIndex: 1,
  visibilityMiles: 10,
  windDirection: "WSW",
  windSpeed: "15 mph",
}
